Servers = 8
Simulation = "ChainBoost"
BF = 2
Rounds = 100
timeout = 12000000
RunWait = "12000000s"
Suite = "bn256.adapter"
FileSizeDistributionMean = 115
FileSizeDistributionVariance = 5
ServAgrDurationDistributionMean = 40
ServAgrDurationDistributionVariance = 20
PercentageTxPay = 30
PayPercentOfTransactions = 0.02
NumberOfPayTXsUpperBound = 100
SectorNumber = 2
NumberOfActiveContractsPerServer = 64
SimulationRounds = 330
SimulationSeed = 100
NbrSubTrees = 1
CommitteeWindow = 500
Threshold = 334
StoragePaymentEpoch = 0
MCRoundPerEpoch = 10
SCRoundPerEpoch = 30
MCRoundDuration = 30
SCRoundDuration = 10
DailyVolume = 25000000
BlockTime = 4  
SwapRate  = 0.9319
BurnRate  = 0.0238
CollectRate = 0.0227
MintRate  = 0.0214
VMs = ["192.168.3.220", "192.168.3.221", "192.168.3.222", "192.168.3.223", "192.168.3.224", "192.168.3.225", "192.168.3.226", "192.168.3.227"]
UsersNbr = 40000
Nodes = 8000
DepositMode = 0

Hosts, SimState, MainChainBlockSize, SideChainBlockSize 
8000, 2, 1000000, 1000000